name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - master
      - 0.29.x

jobs:
  CI:
    name: (${{ matrix.os }}, ${{ matrix.python-version }}, ${{ matrix.backend }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: [3.6, 3.7, 3.8]
        backend: [c, cpp]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}

    - name: Conda info
      shell: bash -l {0}
      run: conda info

    - name: Install Test Requirements
      shell: bash -l {0}
      run: |
        conda install -c conda-forge numpy=1.18.* pythran
        conda install jupyter line_profiler pyzmq pyrsistent qtconsole 

    - name: Build Cython
      shell: bash -l {0}
      run: python setup.py build_ext -i -j2
      env:
        CFLAGS: "-O2 -ggdb -Wall -Wextra"

    - name: Run Test
      shell: bash -l {0}
      run: python runtests.py -vv --no-code-style --backends=${{ matrix.backend }}
      env:
        CFLAGS: "-O0 -ggdb -Wall -Wextra"
